import Link from "next/link";
import Head from "next/head";
import axios from "axios";
import { Context } from "./context/context";
import { useContext, useEffect } from "react";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const context = useContext(Context);
  useEffect(() => {
    const options = {
      method: "GET",
      url: "http://localhost:3000/api/mailchimp",
    };
    axios
      .request(options)
      .then(function (response) {
        context.dispatch({ type: "contacts", payload: response.data });
      })
      .catch(function (error) {
        console.error(error);
      });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <>
      <Head>
        <title>Contact View</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          {" "}
          <Link href={`/add`}>
            <button>Add</button>
          </Link>
        </div>
        <div>
          {context.state.contacts.map((el) => {
            return (
              <>
                <Link
                  href={{
                    pathname: "/contact",
                    query: { id: el.email.address },
                  }}
                >
                  <p>{el.email.address}</p>
                </Link>
              </>
            );
          })}
        </div>
      </main>
    </>
  );
}
