import Form from "@/components/Form";
import axios from "axios";
import Link from "next/link";
import React, { useState } from "react";
import Head from "next/head";
import Loading from "@/components/Loading";
export default function Add() {
  const [file, setFile] = useState<File | null>(null);
  const [state, setState] = useState({
    message: "",
    popup: false,
    charging: false,
    dataError: [{ email: "" }],
  });
  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setState((prev) => ({
      ...prev,
      charging: true,
    }));
    if (!file) {
      return;
    }
    const options = {
      method: "POST",
      url: `http://localhost:3000/api/mailchimp/csv`,
      data: file,
    };
    axios
      .request(options)
      .then(function (response) {
        setState((prev) => ({
          ...prev,
          message: response.data.message,
          popup: true,
          charging: false,
          dataError: response.data.dataError,
        }));
        console.log(response.data);
      })
      .catch(function (error) {
        console.log(error);
        setState((prev) => ({
          ...prev,
          message: error.response.data.message,
          popup: true,
          charging: false,
        }));
      });
  };
  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = e.target.files?.[0];
    setFile(selectedFile || null);
  };
  return (
    <div>
      <Head>
        <title>Contact View</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href={`/`}>
        <p style={{ fontSize: "x-large", textAlign: "center" }}>Home</p>
      </Link>
      <Form />
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          color: "#e0e1dd",
        }}
      >
        <h4 style={{ fontSize: "x-large" }}>Send a CSV File</h4>
        <form onSubmit={handleSubmit}>
          <label htmlFor="csv-file">Select a CSV file: </label>
          <input
            type="file"
            id="csv-file"
            accept=".csv"
            onChange={handleFileChange}
          />
          <button type="submit"> Send </button>
        </form>
        {state.charging && <Loading />}
        {state.popup && (
          <>
            <p>{state.message}</p>{" "}
            <button
              onClick={() => {
                setState((prev) => ({ ...prev, popup: false, dataError: [] }));
              }}
            >
              Close
            </button>
            {state.dataError.length > 0 && (
              <>
                <h3>Contacts do not load</h3>
                {state.dataError.map((el) => (
                  <p key={el?.email}>{el?.email}</p>
                ))}
              </>
            )}
          </>
        )}
      </div>
    </div>
  );
}
