import axios from "axios";
import React from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import { Context } from "@/context/context";
import Form from "@/components/Form";
import Head from "next/head";
export default function Edit() {
  const context = React.useContext(Context);
  const router = useRouter();
  const { id } = router.query;
  const contact = context.state.contact;
  React.useEffect(() => {
    if (id) {
      const options = {
        method: "GET",
        url: `http://localhost:3000/api/mailchimp?id=${id}`,
      };
      axios
        .request(options)
        .then(function (response) {
          context.dispatch({ type: "contact", payload: response.data[0] });
        })
        .catch(function (error) {
          console.error(error);
        });
    }
    return () => {
      context.dispatch({
        type: "contact",
        payload: {
          systemRecordId: "",
          dateChanged: "",
          email: { address: "" },
        },
      });
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id]);
  return (
    <div>
      <Head>
        <title>Contact View</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href={`/`}>
        <p style={{ fontSize: "x-large", textAlign: "center" }}>Home</p>
      </Link>
      <Form contact={contact} />
    </div>
  );
}
